POST  http://localhost:5000/api/auth/register
Content-Type:  application/json

{
    "email": "recruiter2@gmail.com",
    "password": "123123",
    "fullname": "Tuan Da",
    "role": "recruiter"
}

###
POST  http://localhost:5000/api/auth/login
Content-Type:  application/json

{
    "email": "recruiter@gmail.com",
    "password": "123123"
}

###
DELETE http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicGhhbWFuaHR1YW5AZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ4MDc4OTUsImV4cCI6MTY2NDgxNTA5NX0.P6Fdl8ePyXLlJFMZFjjBj7sPKA0i8AMrn67Q_If1f0Y


###
POST  http://localhost:5000/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicGhhbWFuaHR1YW5AZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ4MDc4OTUsImV4cCI6MTY2NDgxNTA5NX0.P6Fdl8ePyXLlJFMZFjjBj7sPKA0i8AMrn67Q_If1f0Y
Content-Type:  application/json

{
    "address": "Hà Tĩnh"
}

###
POST http://localhost:5000/api/job/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoicmVjcnVpdGVyQGdtYWlsLmNvbSIsInJvbGUiOiJyZWNydWl0ZXIiLCJpYXQiOjE2NjQ4NDQwNjUsImV4cCI6MTY2NDg1MTI2NX0.ksJzTh7L3ou-dgktOE_8Q0qm2l-r1VtecMJb5k2t1pU
Content-Type:  application/json

{
    "title": "Tìm HR cho công ty",
    "content": "Tao tuyển mày về làm mình làm mẩy oke a ba la trap khè khè khè",
    "salary": "Từ 20 triệu",
    "level": "Senior",
    "skills": "reactjs",
    "location": "Đà nẵng",
    "welfare": "Tăng lương 2 lần 1 năm",
    "amount": "5 nguoi",
    "workFrom": "fulltime",
    "endDate": "20/10/2022",
    "isDeleted": false,
    "jobCategoryId": 2
} 

###
GET http://localhost:5000/api/job/

###
GET http://localhost:5000/api/user/3
