POST  http://localhost:5000/api/auth/register
Content-Type:  application/json

{
    "email": "tuandanew2@gmail.com",
    "password": "123123",
    "fullname": "Tuan Da"
}
 
###
POST  http://localhost:5000/api/auth/login
Content-Type:  application/json

{
    "email": "recruiter-test@gmail.com",
    "password": "123123"
}

###
DELETE http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicGhhbWFuaHR1YW5AZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ4MDc4OTUsImV4cCI6MTY2NDgxNTA5NX0.P6Fdl8ePyXLlJFMZFjjBj7sPKA0i8AMrn67Q_If1f0Y


###
POST  http://localhost:5000/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicGhhbWFuaHR1YW5AZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ4MDc4OTUsImV4cCI6MTY2NDgxNTA5NX0.P6Fdl8ePyXLlJFMZFjjBj7sPKA0i8AMrn67Q_If1f0Y
Content-Type:  application/json

{
    "address": "Hà Tĩnh"
}

###
POST http://localhost:5000/api/job/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjMxODI3OC1kYzdhLTRjODUtYjc5ZS03MmU0NjA3MDFjZjIiLCJlbWFpbCI6InJlY3J1aXRlci10ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJyZWNydWl0ZXIiLCJpYXQiOjE2NjUyNTIzNzksImV4cCI6MTY2NTI1OTU3OX0.PbrVWrWzsrYnWfKQcj4H7DdL20IganQK_-ThA4Jqnvw
Content-Type:  application/json

{
    "title": "Trần ngạc đâng phưng",
    "content": "hé lô",
    "salary": "Từ 20 triệu",
    "level": "Senior",
    "skills": "reactjs",
    "location": "Đà nẵng",
    "welfare": "Tăng lương 2 lần 1 năm",
    "amount": "5 nguoi",
    "workFrom": "fulltime",
    "endDate": "20/10/2022",
    "categoryId": 10,
    "isDeleted": false,
    "jobCategoryId": 2
} 

###
GET http://localhost:5000/api/job/category/10


###
GET http://localhost:5000/api/job/

###
GET http://localhost:5000/api/user/5

### 
POST http://localhost:5000/api/assess/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJwaGFtYW5odHVhbkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NTIyMDU4OCwiZXhwIjoxNjY1MjI3Nzg4fQ.NL71Vu8t5zgYKChR734gG0m6sabP90tnoVvQzoa3EV8
Content-Type:  application/json

{
    "message": "Cmt test migrations"
}

###
GET http://localhost:5000/api/user/3

###
PUT http://localhost:5000/api/job/b1993b69-3b61-45da-9824-4a63ee2f522a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjMxODI3OC1kYzdhLTRjODUtYjc5ZS03MmU0NjA3MDFjZjIiLCJlbWFpbCI6InJlY3J1aXRlci10ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJyZWNydWl0ZXIiLCJpYXQiOjE2NjUyMDkwMDksImV4cCI6MTY2NTIxNjIwOX0.BH8OXEhQEOIJJxRgdhnTFIcKULPfWdE1m7krsFHlwsE
Content-Type:  application/json

{
    "title": "Sửa Job của recruiter-test",
    "content": "Đã sửa job rồi nè",
    "salary": "Từ 20 triệu",
    "level": "Senior",
    "skills": "reactjs",
    "location": "Đà nẵng",
    "welfare": "Tăng lương 2 lần 1 năm",
    "amount": "5 nguoi",
    "workFrom": "fulltime",
    "endDate": "20/10/2022",
    "isDeleted": false,
    "jobCategoryId": 2
} 

###
DELETE  http://localhost:5000/api/job/b1993b69-3b61-45da-9824-4a63ee2f522a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjMxODI3OC1kYzdhLTRjODUtYjc5ZS03MmU0NjA3MDFjZjIiLCJlbWFpbCI6InJlY3J1aXRlci10ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJyZWNydWl0ZXIiLCJpYXQiOjE2NjUyMTg4NTMsImV4cCI6MTY2NTIyNjA1M30.qzg_hP7awF5kwyjKazhDN0UJdOe4cCbWW7XZ8z68Veo

###
GET http://localhost:5000/api/job/b1993b69-3b61-45da-9824-4a63ee2f522a

###
DELETE http://localhost:5000/api/assess/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJwaGFtYW5odHVhbkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NTA1NjkzMywiZXhwIjoxNjY1MDY0MTMzfQ.g8uslAYbtneS3MojEUIp7dxIHglNXL_jmpqMa7CQkoI

###
PUT http://localhost:5000/api/assess/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiZW1haWwiOiJwaGFtYW5odHVhbkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY2NTA3NjIwOCwiZXhwIjoxNjY1MDgzNDA4fQ.vbFHVfRxkROeWOeEmS86YAwuVeTFP2LmOZ2WtQ1VPrw
Content-Type:  application/json

{
    "message": "Đã sửa comment"
}